# app/models/__init__.py
"""
Database models package
"""

from .admin import AdminLog, SystemMetrics
from .base import BaseModel, db
from .contact import (
    AddressType,
    AgeGroup,
    ClearanceStatus,
    Contact,
    ContactAddress,
    ContactEmail,
    ContactOrganization,
    ContactPhone,
    ContactRole,
    ContactStatus,
    ContactTag,
    ContactType,
    EducationLevel,
    EmailType,
    EmergencyContact,
    Gender,
    LocalStatus,
    OrganizationType,
    PhoneType,
    PreferredLanguage,
    RaceEthnicity,
    RoleType,
    Salutation,
    Student,
    Teacher,
    Volunteer,
    VolunteerAvailability,
    VolunteerHours,
    VolunteerInterest,
    VolunteerOrganizationStatus,
    VolunteerSkill,
    VolunteerStatus,
)
from .event import (
    CancellationReason,
    Event,
    EventFormat,
    EventOrganization,
    EventStatus,
    EventType,
    EventVolunteer,
    EventVolunteerRole,
    RegistrationStatus,
)
from .feature_flag import OrganizationFeatureFlag, SystemFeatureFlag
from .importer import (
    ChangeLogEntry,
    CleanEvent,
    CleanOrganization,
    CleanVolunteer,
    DataQualitySeverity,
    DataQualityStatus,
    DataQualityViolation,
    DedupeDecision,
    DedupeSuggestion,
    ExternalIdMap,
    ImporterWatermark,
    ImportRun,
    ImportRunStatus,
    ImportSkip,
    ImportSkipType,
    MergeLog,
    StagingEvent,
    StagingOrganization,
    StagingRecordStatus,
    StagingVolunteer,
)
from .organization import Organization, OrganizationAddress
from .role import Permission, Role, RolePermission, UserOrganization
from .user import User

__all__ = [
    "db",
    "BaseModel",
    "User",
    "AdminLog",
    "SystemMetrics",
    "Organization",
    "OrganizationAddress",
    "Role",
    "Permission",
    "RolePermission",
    "UserOrganization",
    "OrganizationFeatureFlag",
    "SystemFeatureFlag",
    # Event models
    "Event",
    "EventOrganization",
    "EventVolunteer",
    # Event enums
    "EventType",
    "EventStatus",
    "EventFormat",
    "CancellationReason",
    "EventVolunteerRole",
    "RegistrationStatus",
    # Contact models
    "Contact",
    "ContactEmail",
    "ContactPhone",
    "ContactAddress",
    "ContactRole",
    "ContactOrganization",
    "ContactTag",
    "EmergencyContact",
    "Volunteer",
    "Student",
    "Teacher",
    # Contact enums
    "ContactType",
    "ContactStatus",
    "RoleType",
    "EmailType",
    "PhoneType",
    "AddressType",
    "AgeGroup",
    "Gender",
    "RaceEthnicity",
    "EducationLevel",
    "Salutation",
    "ClearanceStatus",
    "PreferredLanguage",
    "LocalStatus",
    "OrganizationType",
    "VolunteerOrganizationStatus",
    # Volunteer models
    "VolunteerSkill",
    "VolunteerInterest",
    "VolunteerAvailability",
    "VolunteerHours",
    "VolunteerStatus",
    # Importer models
    "ImportRun",
    "ImportRunStatus",
    "StagingVolunteer",
    "StagingOrganization",
    "StagingEvent",
    "StagingRecordStatus",
    "DataQualityViolation",
    "DataQualitySeverity",
    "DataQualityStatus",
    "DedupeSuggestion",
    "DedupeDecision",
    "ExternalIdMap",
    "MergeLog",
    "ChangeLogEntry",
    "CleanVolunteer",
    "CleanOrganization",
    "CleanEvent",
    "ImportSkip",
    "ImportSkipType",
    "ImporterWatermark",
]
